pipeline {
  agent any
  stages {
    stage('Pre-Staging') {
      steps {
        sh 'pwd'
        sh 'ls -lahrt'
        sh 'ls -lahrt CNE-Practical-Project/infrastructure/jenkins'
        sh 'ls -lahrt CNE-Practical-Project/infrastructure/ansible'
        sh 'cat .gitignore'
      }
    }

  }
}