pipeline {
  agent any
  stages {
    stage('Pre-Staging') {
      steps {
        sh 'pwd'
        sh 'ls -lahrt'
        sh 'cd CNE-Practical-Project'
        sh 'ls -lahrt infrastructure/jenkins'
        sh 'ls -lahrt infrastructure/ansible'
        sh 'cat .gitignore'
      }
    }

  }
}