---
- hosts: "localhost"

  tasks:
    # I am planning to use Jenkins-Dockerhub plugin to push images
    # https://github.com/jenkinsci/dockerhub-notification-plugin/blob/master/README.md
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#examples
    - name: build test version of backend image
      community.docker.docker_image:
        build:
          path: ./backend
        name: sashumi/cne_backend
        tag: test
        source: build
        force_source: yes
        force_tag: yes
      tags:
        - never
        - image_test

    - name: build test version of frontend image
      community.docker.docker_image:
        build:
          path: ./frontend
        name: sashumi/cne_frontend
        tag: test
        source: build
        force_source: yes
        force_tag: yes
      tags:
        - never
        - image_test

    - name: build test version of database image
      community.docker.docker_image:
        build:
          path: ./database
        name: sashumi/cne_database
        tag: test
        source: build
        force_source: yes
        force_tag: yes
      tags:
        - never
        - image_test


    - name: push test version of backend image
      community.docker.docker_image:
        build:
          path: ./backend
        name: sashumi/cne_backend
        tag: test
        source: local
        push: yes
      tags:
        - never
        - image_test

    - name: push test version of frontend image
      community.docker.docker_image:
        build:
          path: ./frontend
        name: sashumi/cne_frontend
        tag: test
        source: local
        push: yes
      tags:
        - never
        - image_test

    - name: push test version of database image
      community.docker.docker_image:
        build:
          path: ./database
        name: sashumi/cne_database
        tag: test
        source: local
        push: yes
      tags:
        - never
        - image_test

    - name: Tag and push backend to docker hub
      community.docker.docker_image:
        name: sashumi/cne_backend:test
        repository: sashumi/cne_backend:latest
        push: yes
        source: local
      tags:
        - never
        - publish_image

    - name: Tag and push frontend to docker hub
      community.docker.docker_image:
        name: sashumi/cne_frontend:test
        repository: sashumi/cne_frontend:latest
        push: yes
        source: local
      tags:
        - never
        - publish_image

    - name: Tag and push database to docker hub
      community.docker.docker_image:
        name: sashumi/cne_database:test
        repository: sashumi/cne_database:latest
        push: yes
        source: local
      tags:
        - never
        - publish_image